import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from './Layout'
import { getProducts } from '../services/getProducts'


const Home: NextPage = () => {
	const limit = 10
	const page = 1
	getProducts({limit,page}).then(response => console.log(response))
	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;500;700&display=swap" rel="stylesheet" />
			</Head>
			<Layout/>
		</div>
	)
}

export default Home
