import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ListCategories } from '../app/components/ListCategories'
import { Header } from '../app/container/Header'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;500;700&display=swap" rel="stylesheet" />
      </Head>
      
      <Header/>
     
     
     

      
    </div>
  )
}

export default Home
